//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineScoreCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayersScore
    {
        public int Id { get; set; }
        public int Score { get; set; }
        public Nullable<int> PlayersId { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
