//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineScoreCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamsData
    {
        public int Id { get; set; }
        public int MatchPlayed { get; set; }
        public int Win { get; set; }
        public int Loss { get; set; }
        public Nullable<int> TeamId { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
